### PR TITLE
[#279] Downgraded Guzzle support for PHP to 6.4.

### PR DESCRIPTION
**Pull request by VladimirAus**
### Description

* `guzzlehttp/guzzle` 6 is still required for large projects like [Drupal 9](https://www.drupal.org/project/drupal/issues/3104353).
* If guzzle will only support `^7.2` then [Mailchimp marketing for Drupal](https://www.drupal.org/project/mailchimp_marketing) will be stuck with library version 3.0.27.
* Guzzle 6 is [still supported](https://github.com/guzzle/guzzle/tree/7.2.0#version-guidance) so I propose to keep it as dependency similar to `guzzlehttp/psr7`.

### CODE REVIEW

**Comment by VladimirAus** [comment]
CLA was signed 2.5 weeks ago.

**Comment by bipol-mc** [comment]
@clabot check

**Comment by bipol-mc** [comment]
@cla-bot check

**Comment by bipol-mc** [comment]
Hey @VladimirAus, thanks for the PR, and sorry for the wait.  

Could you also bump the version in [marketing.json](https://github.com/mailchimp/mailchimp-client-lib-codegen/blob/main/spec/marketing.json) and [transactional.json](https://github.com/mailchimp/mailchimp-client-lib-codegen/blob/main/spec/transactional.json).  This informs our deployer to push new artifacts to the package managers.

e.g.
```
diff --git a/spec/marketing.json b/spec/marketing.json
index 3e383d1..67d1f81 100644
--- a/spec/marketing.json
+++ b/spec/marketing.json
@@ -752,7 +752,7 @@
     },
     "swagger": "2.0",
     "info": {
-        "version": "3.0.72",
+        "version": "3.0.73",
         "title": "Mailchimp Marketing API",
         "contact": {
             "name": "Mailchimp API Support",

```

**Comment by VladimirAus** [comment]
@bipol-mc done 😃

**Pull request merged**
