### PR TITLE
We're not properly supporting typescript definitions so lets remove them

### PR DESCRIPTION
**Pull request by mc-hannah-morrison**
### Description
Typescript support wasn't finished, and isn't functioning, so this removes the unhelpful definitions

### CODE REVIEW

**Comment by prichey** [comment]
Works for me! Thanks for doing this. ✂️

**Review by bipol-mc — APPROVED** [review]
Cool, no types in the artifact
```
bipolalam@Bipols-MacBook-Pro mailchimp-marketing-node 2 % ls -al
total 96
drwxr-xr-x@   8 bipolalam  staff    256 Jul 13 14:58 .
drwx------@ 271 bipolalam  staff   8672 Jul 13 14:58 ..
-rw-r--r--@   1 bipolalam  staff     65 Jul 13 14:52 .travis.yml
-rw-r--r--@   1 bipolalam  staff  11975 Jul 13 14:53 LICENSE
-rw-r--r--@   1 bipolalam  staff  22025 Jul 13 14:52 README.md
-rw-r--r--@   1 bipolalam  staff   1663 Jul 13 14:52 git_push.sh
-rw-r--r--@   1 bipolalam  staff    481 Jul 13 14:52 package.json
drwxr-xr-x@   5 bipolalam  staff    160 Jul 13 14:52 src
```

**Comment by xdc0** [comment]
Any plans to support exporting types in the future?

**Comment by dodas** [comment]
I find it unjustifiable that a library like mailchimp does not ship with types.
The definitions at `@types/mailchimp__mailchimp_marketing` are not up to date.

**Comment by manvydasu** [comment]
Not having type-safety support _significantly_ reduces node's client usefulness.

**Comment by wezooyuri** [comment]
Yeah this makes this lib basically unusable. Which is a shame, since the documented API seems way more useful than the alternatives.

**Pull request merged**
