### PR TITLE
Swagger updates with input parameters marked as readOnly removed, and…

### PR DESCRIPTION
**Pull request by mc-hannah-morrison**
… some reorganization of the documentation hierarchy

### Description
Updating the Swagger.

Some of the Swagger fixes include:
- removing input definitions marked as "readOnly". This resulted in Body Parameters displayed in the documentation that are not actually supported.
- remove endpoint definitions for non-functional paths that exist to group endpoints e.g. api.mailchimp.com/3.0/reporting
- use enum to specify campaign content_type options
- clarified date-time string types

### CODE REVIEW

**Comment by Moishe** [comment]
This LGTM (assuming diffs with SDKs look reasonable, or if you feel comfortable not checking them). The bad news is you may need to create a new PR so cla-bot doesn't complain about it.

**Review by prichey — APPROVED** [review]
LGTM!

**Comment by mc-hannah-morrison** [comment]
@cla-bot check

**Comment by mc-hannah-morrison** [comment]
@cla-bot[bot] check

**Pull request merged**
